travis:
  secure:
    BINSTAR_TOKEN: atCREtEbUWaBW9xoEzdN0l6tb0xIwSgBdgOruTBPwM6B0LgT9ClzQ3Pax2d3KQWQJX+XwT4ggB9mWPuIVD23PRwbBrLdLubcBMc51730xHrr6b0Hy7H6aCbduQqq4L9bHot96jft7kh7JrsNuEiTNJDtMak886FpMfecoKNmf/SSrY90EhvKnUdzKjpbC/Rji6skjmd03qEfEOEP5rsPs5cP1P2+e0DJiQgqNOMifCfsypZqLzP1Pd7fW4vOlfnQn3tg5hkCpZCnm1fG7OXIH8CtZbeQYyKUtgKGbYvVPcVQHASvHCibYp/O6fULqQ3LyYBI6XHyXTuIQ4T4qBjUX0N8/lfmOblpDACVb5J0sjSC24q/5qiJojzxbpbj1W7mdQqizLXNCsct/PmibqFd8+1jAgLqFL9E18Pgt9i+yhxvM5AQAX8hamDaw3TOZw/TjkvCK09fmuCR3U9cX1EK/ydkEugG3Z5kGqYT6hcLHMOYHASynX9+EsFkYXAcz3x3w/ToSINHKLr4BJe9XZH8Xg0z2unHmLMGJ3zWD1jkswSsBwdnd+cD2XpRrS+gq6uvqoMARrnVxADHM7dXp47QZEgzTAw8HdGonHlOfQDqkHAq4Bg5JQfWSslqEeJZOiKO6m8jXQVAOrNUIR5yQluqDR3P4nVTx36LC3+TNzhvJtI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
